### ISSUE TITLE
Can't find Parameterizer.sol on fresh install

### ISSUE THREAD

**Issue by rbharath** [computablelabs/contracts#32]
Installing on a fresh environment, and running into some errors:

```
rbharath@rbharath-XPS-13-9360:~/computable$ npm run truffle:compile

> Computable@0.0.1 truffle:compile /home/rbharath/computable
> truffle compile

Error: Could not find /home/rbharath/computable/contracts/Parameterizer.sol from any sources; imported from /home/rbhar$th/computable/contracts/registry.sol
    at /home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/index.js:76:1
    at /home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/~/async/internal$onlyOnce.js:12:1
    at next (/home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/~/async/wh$lst.js:68:1)
    at /home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/index.js:64:1
    at /home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/fs.js:85:1
    at /home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/~/async/internal$once.js:12:1
    at replenish (/home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/~/asy$c/internal/eachOfLimit.js:59:1)
    at iterateeCallback (/home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolve$/~/async/internal/eachOfLimit.js:49:1)
    at /home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-resolver/~/async/internal$onlyOnce.js:12:1
    at ReadFileContext.callback (/home/rbharath/computable/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle$resolver/fs.js:81:1)
```

Any silly mistakes I might be running into? Here's my system details:

```
rbharath@rbharath-XPS-13-9360:~/computable$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
rbharath@rbharath-XPS-13-9360:~/computable$ npm --version
5.6.0
```

**Comment by rbharath** [comment]
Quick offline chat w/ @robrobbins revealed the bug. Needed to change the capitalization in `Registry.sol` import to:

```
import "./parameterizer.sol";
```

Will open a quick PR
